from django.db import models
class User_details(models.Model):
    username = models.TextField()
    email = models.EmailField()
    password = models.CharField(max_length = 16)

class Supply_chain_data(models.Model):
    ADMIN_ID = models.IntegerField()
    PRODUCT_DEVELOPMENT = models.BooleanField()
    PROCUREMENT = models.BooleanField()
    MANUFACTURING = models.BooleanField()
    DISTRIBUTION = models.BooleanField()
    TRANSPORTATION = models.BooleanField()
    SERVICE = models.BooleanField()
    DEMAND_GEN = models.BooleanField()
    FORCASTING = models.BooleanField()
    IT = models.BooleanField()
    OTHER = models.BooleanField()
    R_STUDY = models.BooleanField()

class firm_data(models.Model):
    admin_ID = models.IntegerField()
    simulation = models.IntegerField()
    firm1 = models.CharField(max_length=50)
    firm2 = models.CharField(max_length=50)
    firm3 = models.CharField(max_length=50)
    firm4 = models.CharField(max_length=50)
    firm5 = models.CharField(max_length=50)

class Product_config(models.Model):
    admin_ID = models.IntegerField()
    simulation_id = models.IntegerField()
    category = models.CharField(max_length = 1)
    Alpha = models.IntegerField()
    Beta = models.IntegerField()
    Bandwidth = models.IntegerField()
    Warranty = models.IntegerField()
    Packaging = models.IntegerField()
    Price = models.IntegerField()

class procurement_post(models.Model):
    admin_ID = models.IntegerField()
    simulation_id = models.IntegerField()
    firm_id = models.IntegerField()
    Quarter = models.IntegerField()
    SAC_Responses = models.JSONField()
    Alpha_quantity = models.BigIntegerField()
    Beta_quantity = models.BigIntegerField()
    Supplier_A_Gamma_Quantity = models.BigIntegerField()
    Supplier_B_Gamma_Quantity = models.BigIntegerField()
    Supplier_C_Gamma_Quantity = models.BigIntegerField()
    Supplier_D_Gamma_Quantity = models.BigIntegerField()
    Supplier_B_Delta_Quantity = models.BigIntegerField()
    Supplier_C_Delta_Quantity = models.BigIntegerField()
    Supplier_D_Delta_Quantity = models.BigIntegerField()
    Supplier_E_Delta_Quantity = models.BigIntegerField()
    Supplier_F_Delta_Quantity = models.BigIntegerField()
    Supplier_D_Epsilon_Quantity = models.BigIntegerField()
    Supplier_E_Epsilon_Quantity = models.BigIntegerField()
    Supplier_F_Epsilon_Quantity = models.BigIntegerField()
    Supplier_G_Epsilon_Quantity = models.BigIntegerField()

class procurement_decision_api(models.Model):
    admin_ID = models.IntegerField()
    simulation_id = models.IntegerField()
    firm_id = models.IntegerField()
    Quarter = models.IntegerField()
    SAC_Responses = models.JSONField()
    Alpha = models.JSONField()
    Beta = models.JSONField()
    Gamma = models.JSONField()
    Delta = models.JSONField()
    Epsilon = models.JSONField()
