# Generated by Django 5.0.1 on 2024-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_details_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_chain_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN_ID', models.IntegerField()),
                ('PRODUCT_DEVELOPMENT', models.BooleanField()),
                ('PROCUREMENT', models.BooleanField()),
                ('MANUFACTURING', models.BooleanField()),
                ('DISTRIBUTION', models.BooleanField()),
                ('TRANSPORTATION', models.BooleanField()),
                ('SERVICE', models.BooleanField()),
                ('DEMAND_GEN', models.BooleanField()),
                ('FORCASTING', models.BooleanField()),
                ('IT', models.BooleanField()),
                ('OTHER', models.BooleanField()),
                ('R_STUDY', models.BooleanField()),
            ],
        ),
    ]
