# Generated by Django 5.0.1 on 2024-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_supply_chain_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='firm_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.IntegerField()),
                ('simulation', models.IntegerField()),
                ('firm1', models.CharField(max_length=50)),
                ('firm2', models.CharField(max_length=50)),
                ('firm3', models.CharField(max_length=50)),
                ('firm4', models.CharField(max_length=50)),
                ('firm5', models.CharField(max_length=50)),
            ],
        ),
    ]
