# Generated by Django 5.0.1 on 2024-01-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_firm_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.IntegerField()),
                ('simulation_id', models.IntegerField()),
                ('category', models.CharField(max_length=1)),
                ('Alpha', models.IntegerField()),
                ('Beta', models.IntegerField()),
                ('Bandwidth', models.IntegerField()),
                ('Warranty', models.IntegerField()),
                ('Packaging', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
