# Generated by Django 5.0.1 on 2024-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_procurement_decision_api_procurement_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_A_Gamma_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_B_Delta_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_B_Gamma_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_C_Delta_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_C_Gamma_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_D_Delta_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_D_Epsilon_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_D_Gamma_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_E_Delta_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_E_Epsilon_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_F_Delta_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_F_Epsilon_Quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='procurement_post',
            name='Supplier_G_Epsilon_Quantity',
            field=models.BigIntegerField(default=None),
        ),
    ]
