# Generated by Django 5.0.1 on 2024-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_simulation_demand_overall_hyperware_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation_demand',
            name='Overall_Hyperware_cost',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulation_demand',
            name='Overall_Metware_cost',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
