# Generated by Django 5.0.1 on 2024-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_overall_metware_cost_simulation_demand_overall_metaware_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='procurements_fc_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.IntegerField()),
                ('simulation_id', models.IntegerField()),
                ('supplier_A_FC', models.BigIntegerField()),
                ('supplier_B_FC', models.BigIntegerField()),
                ('supplier_C_FC', models.BigIntegerField()),
                ('supplier_D_FC', models.BigIntegerField()),
                ('supplier_E_FC', models.BigIntegerField()),
                ('supplier_F_FC', models.BigIntegerField()),
                ('supplier_G_FC', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier_Relationship_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.IntegerField()),
                ('simulation_id', models.IntegerField()),
                ('Relation_Object', models.JSONField()),
            ],
        ),
    ]
