# Generated by Django 5.0.1 on 2024-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_manufacturing_decision_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing_decision_table',
            name='production_hyperware_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing_decision_table',
            name='production_metaware_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing_decision_table',
            name='production_product_0_units',
            field=models.IntegerField(null=True),
        ),
    ]
